# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    project4OC\BookingBundle\FormatDate\:
        resource: '../../src/project4OC/BookingBundle/FormatDate/*'

    project4OC\BookingBundle\VerifyAvailableDate\:
        resource: '../../src/project4OC/BookingBundle/VerifyAvailableDate/*'

    project4OC\BookingBundle\Stripe\:
        resource: '../../src/project4OC/BookingBundle/Stripe/*'

    project4OC\BookingBundle\Entity\:
        resource: '../../src/project4OC/BookingBundle/Entity/*'

    project4OC\BookingBundle\Controller\:
        resource: '../../src/project4OC/BookingBundle/Controller'
        public: true
        tags: ['controller.service_arguments']