<?php

namespace project4OC\BookingBundle\Repository;

/**
 * VisitDayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitDayRepository extends \Doctrine\ORM\EntityRepository
{
}
